//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASRestaurant.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public int ContactID { get; set; }
        public string Status { get; set; }
        public string ResponseMessage { get; set; }
        public Nullable<System.DateTime> CreateMessageDate { get; set; }
        public Nullable<System.DateTime> ResponseMessageDate { get; set; }
    }
}
