//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HASRestaurant.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int couponID { get; set; }
        public string couponCode { get; set; }
        public int discount { get; set; }
    }
}
